// <auto-generated />
namespace Green.Alunos.Repositorio.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Aluno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aluno));
        
        string IMigrationMetadata.Id
        {
            get { return "201807172356051_Aluno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
