// <auto-generated />
namespace Green.Album.Autenticado.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_Field_NomeCompleto_Entity_ApplicationUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Field_NomeCompleto_Entity_ApplicationUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201807172204217_Add_Field_NomeCompleto_Entity_ApplicationUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
