//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Green.AlbumCopa2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogador
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Pais { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
    }
}
